server:
  port: 8888

spring:
  application:
    name: ead-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Ismadrade/ead-config-server-repo
          default-label: main
          username: ismadrade
          password: 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

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost
